---
title: "3mt_examples_analysis" 
author: "Sammi Johnson"
date: "2026-01-08"
output: html_document
editor_options: 
  markdown: 
    wrap: 80
---

# 3MT

## Intro

### Relate to a general audience/i.e. why do we care?

-   Abiotic stresses on crops, such as drought or nutrient stress, affect
    millions of people every year to the tune of billions of dollars of lost
    value for farmers, and contribute to rising food prices/lower availability
    for everyone

-   Climate change is projected to worsen these, either directly through
    desertification, or indirectly

-   Strawberry alone is a high value crop (3 billion/yr in the US), with China
    being the largest producer

-   Can't use soil fumigants forever, methyl bromide messes up the ozone (phased
    out in 2016 with the Montreal protocol), and replacements don't work nearly
    as well

### Describe the problem/gap in current understanding

-   The microbiome in a plant's root system and surrounding soil plays an
    important role in the management of these stresses
-   Still mysterious how this all works, but important to find the underlying
    patterns
-   We know from previous research that among other crops, strawberries are able
    to recruit from a pool of existing microbes in the soil to promote systemic
    resistance to disease and increase nutrient uptake
-   Research mostly focused on biotic stress, more in-depth research is needed
    for abiotic stresses
-   Mitigating these without damaging the environment further with pollutants
    like bromine-based fumigants to control will be more important with every
    passing year as we face the effects of climate change

## Research Question

*Why is this the case? Are there certain risk and resilience factors that can
help explain these different trajectories?*

We've recently established that strawberries can indeed recruit helpful microbes
from the surrounding soil to induce disease resistance, and even some
significant evidence that this influences nutrient uptake. But the mechanism and
plasticity of these effects remain unknown, and determining those depends on
teasing out those genotype by environment effects. What are those effects?

## Proposed Study

To answer this question, I'll use the same list of cultivars in Lazcano Boyd et
al '21 for consistency's sake (unless a better cross section of comm. 🍓
cultivars re: abiotic stress resistance can be determined). Trial overview:

-   20 plants per plot, 0.3m raised beds
-   Treatment:
    -   field soil\* with various\*\* macronutrient and drought stress factor
        levels
-   Control:
    -   field soil\*, standardized watering and fertilizer regimen

Field soil measured by soil classification, texture, slope, conductivity, pH,
cation exchange capacity, and percent organic matter. Additionally, levels of
the specific, tested nutrient levels affected by the treatment groups will be
measured as follows:

-   Ca:Mg ratio
-   Water content (neutron moisture gauge)
-   NPK

## 

### Research Goal (What do you hope to find out with this study?)

The goal of this study is to determine what patterns, if any, exist between the
rhizosphere microbiome composition and strawberry drought resistance and
nutrient uptake. With this information in hand, we'll have valuable.
